# 基础镜像
FROM redis
# author
MAINTAINER spzx

# 挂载目录
VOLUME /home/spzx/redis
# 创建目录
RUN mkdir -p /home/spzx/redis
# 指定路径
WORKDIR /home/spzx/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/spzx/redis/redis.conf
