# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER spzx

# 挂载目录
VOLUME /home/spzx
# 创建目录
RUN mkdir -p /home/spzx
# 指定路径
WORKDIR /home/spzx
# 复制jar文件到路径
COPY ./jar/spzx-visual-monitor.jar /home/spzx/spzx-visual-monitor.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","spzx-visual-monitor.jar"]
